# Generated by Django 6.0.2 on 2026-03-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INTERN', 'Intern'), ('EMPLOYER', 'Employer')], max_length=10)),
                ('cv', models.FileField(blank=True, help_text='Upload your CV/Resume (PDF preferred)', null=True, upload_to='cvs/%Y/%m/%d/', verbose_name='Curriculum Vitae (CV)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
