# Generated by Django 6.0.2 on 2026-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('EMPLOYER', 'Employer'), ('INTERN', 'Intern')], max_length=20),
        ),
    ]
