# Generated by Django 6.0.2 on 2026-03-05 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 5, 13, 31, 21, 283464, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
