# Generated by Django 6.0.2 on 2026-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Programming, Design, Marketing', max_length=80),
        ),
    ]
