# Generated by Django 6.0.2 on 2026-03-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_create_userskill_table'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='profile',
            field=models.ForeignKey(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.profile'),
        ),
    ]
